[package]
name = "ue-ra-client"
version = "0.1.0"
authors = ["Yu Ding <dingyu02@baidu.com>"]

[dependencies]
chrono      = "0.4.5"
webpki      = "0.21"
rustls      = { version = "0.15.2", git = "https://github.com/ctz/rustls", features = ["dangerous_configuration"], rev = "056d843c0b96ea5ccf7837da3b2de33a87fc0c28" }
itertools   = "*"
sgx_types   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
base64      = "0.9.2"
serde_json  = "1.0"
num-bigint  = "*"
bit-vec     = "*"
hex         = "*"
