[package]
name = "tr-mpc-client"
version = "0.1.0"
authors = ["Webb Shi <bradyjoestar@gmail.com>"]

[dependencies]
chrono      = "0.4.5"
webpki      = "0.21"
rustls      = { version = "0.15.2", git = "https://github.com/ctz/rustls", features = ["dangerous_configuration"], rev = "056d843c0b96ea5ccf7837da3b2de33a87fc0c28" }
itertools   = "*"
sgx_types   = { path = "../../../sgx_types" }
base64      = "0.9.2"
serde_json  = "1.0"
num-bigint  = "*"
bit-vec     = "*"
hex         = "*"
